definitions:
  datasets:
    olga_dataset:
      format: OLGA
      params:
        path: ".\\data\\olga_repertoires"
        is_repertoire: True # whether to import a RepertoireDataset (True) or a SequenceDataset (False)
        metadata_file: ".\\data\\metadata.csv" # metadata file for RepertoireDataset
        import_illegal_characters: False # remove sequences with illegal characters for the sequence_type being used
        import_empty_nt_sequences: True # keep sequences even though the nucleotide sequence might be empty
        import_empty_aa_sequences: False # filter out sequences if they don't have sequence_aa set
        # Optional fields with OLGA-specific defaults, only change when different behavior is required:
        # separator: "\t" # column separator
        # region_type: IMGT_CDR3 # what part of the sequence to import
  encodings:
    continuous_kmer:
      KmerFrequency:
        normalization_type: RELATIVE_FREQUENCY
        reads: UNIQUE
        sequence_encoding: CONTINUOUS_KMER
        sequence_type: NUCLEOTIDE
        k: 3
        scale_to_unit_variance: True
        scale_to_zero_mean: True
instructions:
  export_instruction:
    type: DatasetExport
    datasets: 
        - olga_dataset
    number_of_processes: 4
      export_formats:
        - AIRR
        - ImmuneML
output:
  format: HTML