datasets:
  real:
    path: ./data/encoded_real.csv
  sim:
    path: ./data/encoded_sim.csv
reports:
  # ks:
  #   - TGT
  distr_histogram:
    - TGT
  # - multivariate
  # - ml-model
  # - pca
  # - copulas
