datasets:
  real:
    path: ./data/encoded_real_1000_200.csv
  sim:
    path: ./data/encoded_sim_1000_200.csv
reports:
  ks:
    - TGT
    - ANV
  distr_histogram:
    - TGT
    - ANV
  observation_distr_histogram:
    - 0
    - 199
    - 200
  distr_boxplot:
    - TGT
    - ANV
  observation_distr_boxplot:
    - 0
    - 199
    - 200
  distr_violinplot:
    - TGT
    - ANV
  observation_distr_violinplot:
    - 0
    - 199
    - 200
  distr_densityplot:
    - TGT
    - ANV
  observation_distr_densityplot:
    - 0
    - 199
    - 200
  distance:
    - TGT
    - ANV
  observation_distance:
    - 0
    - 199
    - 200
  statistics:
    - TGT
    - ANV
  observation_statistics:
    - 0
    - 199
    - 200
  copula_2d:
    report1:
      - TGT
      - ANV
  copula_3d:
    report1:
      - TGT
      - ANV
      - CAS
  feature_average_vs_variance:
  observation_average_vs_variance:
  corr:
    percent_features: 1.0
  pca_2d:
# output:
#   path: report.html
