datasets:
  real:
    path: ./data/real_data.csv
  sim:
    path: ./data/sim_data.csv
reports:
  feature_based:
    report1:
      features:
        - CAS
        - SAS
      report_types:
        - ks
        - distr_histogram
        - distr_boxplot
        - distr_violinplot
        - distr_densityplot
        - distance
        - statistics
  observation_based:
    report1:
      observations:
        - 20
      report_types:
        - ks
        - distr_histogram
        - distr_boxplot
        - distr_violinplot
        - distr_densityplot
        - distance
        - statistics
    report2:
      observations:
        - all
      report_types:
        - distr_densityplot
  general:
    copula_2d:
      report1:
        - CAS
        - SAS
    copula_3d:
      report1:
        - CAS
        - SAS
        - TGT
    feat_mean_vs_variance:
    obs_mean_vs_variance:
    corr:
    corr_feat_hist:
      n_bins: 30
    corr_obs_hist:
      n_bins: 20
      with_ml_sim: True
      ml_random_state: 0
    pca_2d_feat:
    pca_2d_obs:
    corr_csv:
      output: ./output/corr.csv
    ks_feat:
      output: ./output/ks_feat.csv
    ks_obs:
      output: ./output/ks_obs.csv
    statistics_feat:
      output_dir: ./output/
    statistics_obs:
      output_dir: ./output/
    distance_feat:
      output: ./output/dist.csv
    distance_obs:
      output: ./output/obs_dist.csv
    jensen_shannon_feat:
      output: ./output/jenshan.csv
    jensen_shannon_obs:
      output: ./output/obs_jenshan.csv
output:
  path: ./output/report.html
