datasets:
  real:
    path: ./data/encoded_real_1000_200.csv
  sim:
    path: ./data/encoded_sim_1000_200.csv
reports:
  # ks:
  #   - TGT
  #   - ANV
  # distr_histogram:
  #   - TGT
  #   - ANV
  # distr_boxplot:
  #   - TGT
  #   - ANV
  distr_violinplot:
    - TGT
    - ANV
  distr_densityplot:
    - TGT
    - ANV
  distance:
    - TGT
    - ANV
  statistics:
    - TGT
    - ANV
  # corr:
  #   percent_features: 0.10
  # pca_2d:
# output:
#   path: report.html
