datasets:
  real:
    path: ./data/encoded_real_1000_200.csv
  sim:
    path: ./data/encoded_sim_1000_200.csv
reports:
  ks:
    - TGT
    - ANV
  distr_histogram:
    - TGT
    - ANV
  distr_boxplot:
    - TGT
    - ANV
  corr:
    percent_features: 0.10
  pca_2d:
