datasets:
  real:
    path: ./data/encoded_real_1000_200.csv
  sim:
    path: ./data/encoded_sim_1000_200.csv
reports:
  feature_based:
    report1:
      features:
        - TGT
        - ANV
      report_types:
        - ks
        - distr_histogram
        - distr_boxplot
        - distr_violinplot
        - distr_densityplot
        - distance
        - statistics
    report2:
      features:
        - _all_
      report_types:
        - distr_densityplot
  observation_based:
    report1:
      observations:
        - 0
      report_types:
        - observation_distr_histogram
        - observation_distr_boxplot
        - observation_distr_violinplot
        - observation_distr_densityplot
        - observation_distance
        - observation_statistics
    report2:
      observations:
        - _all_
      report_types:
        - observation_distr_densityplot
      with_ml_sim: True
      ml_random_state: 0
  general:
    copula_2d:
      report1:
        - TGT
        - ANV
    copula_3d:
      report1:
        - TGT
        - ANV
        - CAS
    feature_average_vs_variance:
      with_ml_sim: True
      ml_random_state: 0
    observation_average_vs_variance:
      with_ml_sim: True
      ml_random_state: 0
    corr:
      with_ml_sim: True
      ml_random_state: 0
      reduce_to_n_features: 150
    pca_2d:
      with_ml_sim: True
      ml_random_state: 0
    corr_csv:
      output: ./output/corr.csv
    ks:
      output: ./output/ks.csv
    statistics:
      output_dir: ./output/
    observation_statistics:
      output_dir: ./output/
    distance:
      output: ./output/dist.csv
    observation_distance:
      output: ./output/obs_dist.csv
    jensen_shannon:
      output: ./output/jenshan.csv
    observation_jensen_shannon:
      output: ./output/obs_jenshan.csv
output:
  path: ./output/report.html
